POST http://localhost:9200/people/_search
Content-Type: application/json

{
  "query":{
    "match":{
      "title":"ElasticSearch"
    }
  } ,
  "sort":{
    "publish_date":{"order":"asc"}
  }
}

###